import Header from "./components/Header"



export default function App(){  
  return (
    <>
    <Header/>
    </>
  )
}

/*
LIBRARIES->
COLLECTION OF REUSABLE CODE | REDUCE THE NEED TO WRITE REPETITIVE CODE FROM SCRATCH
YOU CONTROL HOW/WHEN ITS USED , NO BOUNDARIES */

/*
FRAMEWORK-> 
PREDETERMINED ARCHITECTURE:EXPECTS TO FOLLOW SPECIFIED PATTERN OF DEVELOPEMENT
WORK WITHIN BOUNDARIES SET BY FRAMEWORK
"RIGHT" AND "WRONG " WAY TO USE IT */

